kind: Namespace
apiVersion: v1
metadata:
  name: flink
  labels:
    name: flink

---
kind: Service
apiVersion: v1
metadata:
  name: flink-jobmanager-svc
spec:
  selector:
    component: flink-jobmanager
  ports:
    - port: 6123
      targetPort: 6123
      name: flink
    - port: 50101
      targetPort: 50101
      name: blobserver
---
kind: Service
apiVersion: v1
metadata:
  name: flink-jobmanager-webui-svc
spec:
  type: NodePort
  selector:
    component: flink-jobmanager
  ports:
    - port: 8081
      targetPort: 8081
      name: http
      nodePort: 31881
---
kind: Deployment
apiVersion: apps/v1
metadata:
  name: flink-jobmanager
spec:
  replicas: 1
  selector:
    matchLabels:
      component: flink-jobmanager
  template:
    metadata:
      labels:
        component: flink-jobmanager
    spec:
      containers:
        - name: flink-jobmanager
          image: lizhiyong2000/flink:1.5.1
          args: ["jobmanager", "jobmanager.rpc.address=flink-jobmanager-svc.flink.svc.cluster.local", "blob.server.port=50101"]
          ports:
            - containerPort: 6123
            - containerPort: 8081
            - containerPort: 50101
          resources:
            requests:
              cpu: 100m
---
kind: Deployment
apiVersion: apps/v1
metadata:
  name: flink-taskmanager
spec:
  replicas: 2
  selector:
    matchLabels:
      component: flink-taskmanager
  template:
    metadata:
      labels:
        component: flink-taskmanager
    spec:
      containers:
        - name: flink-taskmanager
          image: lizhiyong2000/flink:1.5.1
          args: ["taskmanager", "jobmanager.rpc.address=flink-jobmanager-svc.flink.svc.cluster.local", "blob.server.port=50101"]
          ports:
            - containerPort: 6121
            - containerPort: 6122
            - containerPort: 50101
          resources:
            requests:
              cpu: 100m


