apiVersion: v1
kind: Service
metadata:
  name: es-ingest-svc
  labels:
    component: elasticsearch
    role: ingest
spec:
  type: NodePort
  selector:
    component: elasticsearch
    role: ingest
  ports:
  - name: http
    port: 9200
    targetPort: 9200
    nodePort: 30920

---
apiVersion: apps/v1beta1
kind: StatefulSet
metadata:
  name: es-ingest
  labels:
    component: elasticsearch
    role: ingest
spec:
  replicas: 1
  serviceName: es-ingest-svc
  template:
    metadata:
      labels:
        component: elasticsearch
        role: ingest
    spec:
      # initContainers:
      # - name: init-sysctl
      #   image: busybox:1.27.2
      #   command:
      #   - sysctl
      #   - -w
      #   - vm.max_map_count=262144
      #   securityContext:
      #     privileged: true
      containers:
      - name: es-ingest
        image: lizhiyong2000/elasticsearch:6.3.0
        env:
        - name: NAMESPACE
          valueFrom:
            fieldRef:
              fieldPath: metadata.namespace
        - name: NODE_NAME
          valueFrom:
            fieldRef:
              fieldPath: metadata.name
        - name: CLUSTER_NAME
          value: es_cluster
        - name: NODE_MASTER
          value: "false"
        - name: NODE_DATA
          value: "false"
        - name: NODE_INGEST
          value: "true"
        - name: HTTP_ENABLE
          value: "true"
        - name: ES_JAVA_OPTS
          value: -Xms1g -Xmx1g
        - name: NETWORK_HOST
          value: _site_,_lo_
        - name: PROCESSORS
          valueFrom:
            resourceFieldRef:
              resource: limits.cpu
        resources:
          requests:
            cpu: 0.25
          limits:
            cpu: 1
        ports:
        - containerPort: 9200
          name: http
        - containerPort: 9300
          name: transport
        livenessProbe:
          tcpSocket:
            port: transport
          initialDelaySeconds: 30
          timeoutSeconds: 5
          periodSeconds: 10
        readinessProbe:
          httpGet:
            path: /_cluster/health
            port: http
          initialDelaySeconds: 30
          periodSeconds: 10
          timeoutSeconds: 5
        volumeMounts:
        - name: data
          mountPath: /opt/elasticsearch/data
  volumeClaimTemplates:
  - metadata:
      name: data
    spec:
      accessModes: [ "ReadWriteOnce" ]
      resources:
        requests:
          storage: 5Gi
      storageClassName: local-storage
