---
apiVersion: extensions/v1beta1
kind: DaemonSet
metadata:
  name: log-pilot
  namespace: kube-system
  labels:
    k8s-app: log-pilot
    kubernetes.io/cluster-service: "true"
spec:
  template:
    metadata:
      labels:
        kubernetes.io/cluster-service: "true"
    spec:
      tolerations:
      - key: node-role.kubernetes.io/master
        effect: NoSchedule
      containers:
      - name: log-pilot
        # image: registry.cn-hangzhou.aliyuncs.com/acs-sample/log-pilot:0.9-filebeat
        image: lizhiyong2000/log-pilot:0.9-filebeat
        resources:
          limits:
            memory: 200Mi
          requests:
            cpu: 100m
            memory: 200Mi
        env:
          # - name: "FILEBEAT_OUTPUT"
          #   value: "elasticsearch"
          # - name: "ELASTICSEARCH_HOST"
          #   value: "es-data-svc.test-ns.svc.cluster.local"
          # - name: "ELASTICSEARCH_PORT"
          #   value: "9200"
          - name: "FILEBEAT_OUTPUT"
            value: "logstash"
          - name: "LOGSTASH_HOST"
            value: "logstash.test-ns.svc.cluster.local"
          - name: "LOGSTASH_PORT"
            value: "5044"
        volumeMounts:
        - name: sock
          mountPath: /var/run/docker.sock
        - name: root
          mountPath: /host
          readOnly: true
        - name: varlib
          mountPath: /var/lib/filebeat
        - name: varlog
          mountPath: /var/log/filebeat
        securityContext:
          capabilities:
            add:
            - SYS_ADMIN
      terminationGracePeriodSeconds: 30
      volumes:
      - name: sock
        hostPath:
          path: /var/run/docker.sock
      - name: root
        hostPath:
          path: /
      - name: varlib
        hostPath:
          path: /var/lib/filebeat
          type: DirectoryOrCreate
      - name: varlog
        hostPath:
          path: /var/log/filebeat
          type: DirectoryOrCreate
