apiVersion: v1
kind: Service
metadata:
  name: historyserver-svc
  labels:
    component: historyserver-svc
spec:
  # *.hadoop-master.hadoop-cluster.svc.cluster.local
  clusterIP: None
  selector:
    component: historyserver
---

apiVersion: v1
kind: Service
metadata:
  name: historyserver-nodeport
  labels:
    component: historyserver-nodeport
spec:
  type: NodePort
  ports:
  - port: 19888
    targetPort: 19888
    nodePort: 32188
  selector:
    component: historyserver
---

apiVersion: apps/v1beta1
kind: StatefulSet
metadata:
  name: historyserver
spec:
  serviceName: historyserver-svc
  replicas: 1
  template:
    metadata:
      labels:
        component: historyserver
    spec:
      terminationGracePeriodSeconds: 0
      containers:
      - name: historyserver
        image: lizhiyong2000/hadoop:2.8.3
        ports:
        - containerPort: 19888
          name: history-web
        # - containerPort: 9000
        #   name: hdfs
        # command:
           # - "/bin/bash"
           # - "/tmp/hadoop-config/bootstrap.sh"
           # - "-d"
        resources:
          requests:
            memory: "1024Mi"
            cpu: "100m"
          limits:
            memory: "1024Mi"
            cpu: "200m"
        env:
          - name: NODE_TYPE
            value: historyserver
        volumeMounts:
          - name: hadoop-data
            mountPath: /opt/hadoop/data
          - name: hadoop-logs
            mountPath: /opt/hadoop/logs
  volumeClaimTemplates:
  - metadata:
      name: hadoop-data
    spec:
      accessModes: [ "ReadWriteOnce" ]
      resources:
        requests:
          storage: 5Gi
      storageClassName: nfs-storage
  - metadata:
      name: hadoop-logs
    spec:
      accessModes: [ "ReadWriteOnce" ]
      resources:
        requests:
          storage: 1Gi
      storageClassName: nfs-storage
