---
apiVersion: v1
kind: Service
metadata:
  name: kafka-manager-svc
  labels:
    app: kafka-manager-svc
spec:
  type: NodePort
  ports:
  - port: 9000
    targetPort: 9000
    nodePort: 30900
  selector:
    app: kafka-manager
---

kind: Deployment
apiVersion: extensions/v1beta1
metadata:
  name: kafka-manager
spec:
  replicas: 1
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        app: kafka-manager
    spec:
      containers:
        - name: kafka-manager
          # image: quay.io/external_storage/nfs-client-provisioner:latest 
          image: lizhiyong2000/kafka-manager:1.3.3.18
          env:
            - name: ZOO_REPLICAS
              value: "3"
