apiVersion: v1
kind: Service
metadata:
  name: mongodb
  labels:
    name: mongodb
spec:
  type: NodePort
  ports:
  - port: 27017
    targetPort: 27017
    nodePort: 32717
  selector:
    role: mongodb
---
apiVersion: apps/v1beta1
kind: StatefulSet
metadata:
  name: mongodb
spec:
  serviceName: "mongodb"
  replicas: 3
  template:
    metadata:
      labels:
        role: mongodb
        # environment: test
    spec:
      terminationGracePeriodSeconds: 10
      containers:
        - name: mongodb
          image: lizhiyong2000/mongodb:4.1.2
          command:
            - mongod
            - "--replSet"
            - rs0
            # - "--smallfiles"
            - "--noprealloc"
            - "--bind_ip"
            - 0.0.0.0
          ports:
            - containerPort: 27017
          volumeMounts:
            - name: mongo-persistent-storage
              mountPath: /data/db
        - name: mongo-sidecar
          image: cvallance/mongo-k8s-sidecar
          env:
            - name: MONGO_SIDECAR_POD_LABELS
              value: "role=mongodb"
  volumeClaimTemplates:
  - metadata:
      name: mongo-persistent-storage
      annotations:
        storage-class: "nfs-storage"
    spec:
      accessModes: [ "ReadWriteOnce" ]
      resources:
        requests:
          storage: 10Gi
      storageClassName: nfs-storage